#
# ~/.bashrc
#

# autocomplete as sudo as well
if [ "$PS1" ]; then
    complete -cf sudo
fi

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# cool colours for ls
alias ls='ls --color=auto'

# set vim as default editor
export VISUAL=vim
export EDITOR="$VISUAL"

# make chromium default browser
export BROWSER="chromium"

# add ~/.bin to path
export PATH="${PATH}:${HOME}/.bin"

# gitify the prompt
source /usr/bin/gitify-prompt.sh set

# get tab-completion for git
source /usr/share/git/completion/git-completion.bash
