#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

if [ -z "$DISPLAY" ] && [ "$(fgconsole)" -eq 1 ]; then
	exec startx
fi

# add ~/.bin to path
export PATH="${PATH}:${HOME}/.bin"

# yarn
export PATH="$PATH:`yarn global bin`"

# set vim as default editor
export VISUAL=vim
export EDITOR="$VISUAL"

# ruby gems
if which ruby >/dev/null && which gem >/dev/null; then
    PATH="$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH"
fi

