#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

if [ -z "$DISPLAY" ] && [ "$(fgconsole)" -eq 1 ]; then
	exec startx
fi

# add ~/.bin to path
export PATH=$HOME/.bin:$PATH

# set vim as default editor
export VISUAL=vim
export EDITOR="$VISUAL"
